# Generated by Django 6.0.6 on 2026-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireciperequest',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
