# Generated by Django 6.0.6 on 2026-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_weekly_meal_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymealplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklymealplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
